Oglasnik/Models/Legacy/Graficke.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {
    [Table("graficke")]
    public class Graficke : KomponentaBase {

        [Display(Name = "Memorija")]
        public string memorija { get; set; }

        [Display(Name = "Slot")]
        public string slot { get; set; }

        [Display(Name = "Frekvencija memorije")]
        public string frek_memorije { get; set; }

        [Display(Name = "Frekvencija jezgre")]
        public string frek_jezgre { get; set; }

        [Display(Name = "Potrošnja")]
        public string potrosnja { get; set; }

    }
}

Oglasnik/Models/Legacy/Maticne.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {

    [Table("maticne")]
    public class Maticne : KomponentaBase {

        [Display(Name = "Socket")]
        public string socket { get; set; }

        [Display(Name = "Potrošnja")]
        public string potrosnja { get; set; }

        [Display(Name = "Memorija")]
        public string memorija { get; set; }

    }
}

Oglasnik/Models/Legacy/Memorije.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {
    [Table("memorije")]
    public class Memorije : KomponentaBase {

        [Display(Name = "Tip")]
        public string tip { get; set; }

        [Display(Name = "Frekvencija")]
        public string frekvencija { get; set; }

        [Display(Name = "Veličina")]
        public string velicina { get; set; }

    }
}

Oglasnik/Models/Legacy/Oglasi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MySql.Data.Types;

namespace Oglasnik.Models {
    [Table("oglasi")]
    public class Oglasi {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Display(Name="Cijena")]
        public decimal cijena { get; set; }

        [Display(Name = "Naslov")]
        public string naslov { get; set; }

        [Display(Name = "Opis")]
        [DataType(DataType.MultilineText)]
        public string opis { get; set; }

        public DateTime datum_objave { get; set; }

        public string korisnik_id { get; set; }

        public string tip_oglasa { get; set; }

        [NotMapped]
        public ApplicationUser korisnik {
            get {
                using (ApplicationDbContext db = new ApplicationDbContext()) {
                    return db.Users.Find(korisnik_id);
                }
            }
        }
        
    }
}

Oglasnik/Models/Legacy/Pohrana.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {

    [Table("pohrana")]
    public class Pohrana : KomponentaBase {
        
        [Display(Name = "Okretaja/min")]
        public string rpm { get; set; }

        [Display(Name = "Sata verzija")]
        public string sata_ver { get; set; }

        [Display(Name = "Veličina")]
        public string velicina { get; set; }

        [Display(Name = "Brzina čitanja")]
        public string brzina_cit { get; set; }

        [Display(Name = "Brzina pisanja")]
        public string brzina_pis { get; set; }

    }
}

Oglasnik/Models/Legacy/Procesori.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {

    [Table("procesori")]
    public class Procesori : KomponentaBase {
                
        [Display(Name = "Broj jezgri")]
        public string jezgre { get; set; }

        [Display(Name = "Socket")]
        public string socket { get; set; }

        [Display(Name = "Frekvencija")]
        public string frekvencija { get; set; }

        [Display(Name = "Potrošnja")]
        public string potrosnja { get; set; }

    }
}

Oglasnik/Models/Legacy/Psu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Oglasnik.Models {

    [Table("psu")]
    public class Psu : KomponentaBase {
        
        [Display(Name = "Snaga")]
        public string snaga { get; set; }

        
    }
}

Oglasnik/Controllers/OglasiController.cs
using Microsoft.AspNet.Identity;
using Oglasnik.Models;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SelectPdf;
using System.Reflection;

namespace Oglasnik.Controllers {
    public class OglasiController : Controller {
        private OglasnikDbContext db = new OglasnikDbContext();

        // GET: Oglasi
        public ActionResult Index() {
            return Redirect("/");
            return View(db.Oglasi.ToList());
        }

        // GET: Oglasi/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Oglasi oglas = db.Oglasi.Find(id);
            if (oglas == null) {
                return HttpNotFound();
            }

            KomponentaBase komponenta;
            switch (oglas.tip_oglasa) {
                case "graficke":
                    komponenta = db.Graficke.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "maticne":
                    komponenta = db.Maticne.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "memorije":
                    komponenta = db.Memorije.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "psu":
                    komponenta = db.Psu.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "pohrana":
                    komponenta = db.Pohrana.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "procesori":
                    komponenta = db.Procesori.Single(k => k.oglas_id == oglas.Id);
                    break;
                default:
                    throw new Exception("This should never happen!");
            }

            ApplicationUser oglasivac;
            using (ApplicationDbContext appdb = new ApplicationDbContext()) {
                oglasivac = appdb.Users.Find(oglas.korisnik_id);
            }

            ViewBag.Komponenta = komponenta;
            ViewBag.Oglasivac = oglasivac;
            return View(oglas);
        }

		/// <summary>
		/// Akcija koja vraća PDF
		/// </summary>
		/// <returns>pdf file</returns>
		/// <param name="id">id oglasa</param>
        [HttpGet]
        public ActionResult OglasPdf(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Oglasi oglas = db.Oglasi.Find(id);
            if (oglas == null) {
                return HttpNotFound();
            }
            
            KomponentaBase komponenta;
            switch (oglas.tip_oglasa) {
                case "graficke":
                    komponenta = db.Graficke.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "maticne":
                    komponenta = db.Maticne.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "memorije":
                    komponenta = db.Memorije.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "psu":
                    komponenta = db.Psu.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "pohrana":
                    komponenta = db.Pohrana.Single(k => k.oglas_id == oglas.Id);
                    break;
                case "procesori":
                    komponenta = db.Procesori.Single(k => k.oglas_id == oglas.Id);
                    break;
                default:
                    throw new Exception("This should never happen!");
            }

            ApplicationUser oglasivac;
            using (ApplicationDbContext appdb = new ApplicationDbContext()) {
                oglasivac = appdb.Users.Find(oglas.korisnik_id);
            }

            PdfDocument doc = new PdfDocument();
            PdfFont font = doc.AddFont(SelectPdf.PdfStandardFont.Helvetica);
            font.Size = 20;
            PdfPage page = doc.AddPage();

            string html = "<style>*{font-family:sans-serif;} li{margin-bottom:5px;font-size:1.2em;} h1{font-size:1.5em;}</style>";
            html += string.Format("<h1>{0}</h1><hr />", oglas.naslov);
            html += string.Format("<ul><li><strong>Opis:</strong><br />{0}</li>", oglas.opis.Replace("\r\n", "<br>"));

            PropertyInfo[] props = komponenta.GetType().GetProperties();
            Array.Reverse(props);
            foreach (var prop in props) {
                if ((new string[] { "Id", "oglas_id", "oglas" }).Contains(prop.Name)) {
                    continue;
                }
                html += string.Format("<li><strong>{0}:</strong> {1}</li>",
                    prop.CustomAttributes.ElementAt(0).NamedArguments[0].TypedValue.ToString().Replace("\"", ""),
                    komponenta.GetType().GetProperty(prop.Name).GetValue(komponenta));
            }
            html += string.Format("<li><strong>Objavio korisnik:</strong> {0}</li><li><strong>Tel:</strong> {1}</li><li><strong>Cijena:</strong> {2} KN</li><li><strong>Datum:</strong> {3}</li></ul>",
                oglasivac.UserName,
                oglasivac.PhoneNumber,
                oglas.cijena,
                oglas.datum_objave
                );

            PdfHtmlElement content = new PdfHtmlElement(html, "localhost");
            
            page.Add(content);
            return File(doc.Save(), "application/pdf", string.Format("oglas {0}.pdf", oglas.naslov));
        }

        // GET: Oglasi/Create
        [Authorize]
        public ActionResult Create() {
            return View();
        }

        // POST: Oglasi/Create
		/// <summary>
		/// Kreiranje oglasa - svaki oglas sprema se u 2 tablice u bazi:
		/// oglasi (zaglavlje) i ovisno o komponenti u zasebnu tablicu.
		/// </summary>
		/// <param name="oglasi">Oglasi.</param>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize]
        public ActionResult Create([Bind(Include = "Id,naslov,opis,cijena,tip_oglasa")] Oglasi oglasi) {
            if (ModelState.IsValid) {

                oglasi.datum_objave = DateTime.Now;
                oglasi.korisnik_id = User.Identity.GetUserId();
                db.Oglasi.Add(oglasi);
                db.SaveChanges();

                //"ručno" bindanje, switch generiran php skriptom u folderu
                using (OglasnikDbContext dbc = new OglasnikDbContext()) {
                    string tip = oglasi.tip_oglasa;

                    switch (tip.ToLower()) {
                        case "graficke":
                            Graficke gr = new Graficke() {
                                oglas_id = oglasi.Id,
                                proizvodac = Request.Params.Get("proizvodac"),
                                model = Request.Params.Get("model"),
                                memorija = Request.Params.Get("memorija"),
                                slot = Request.Params.Get("slot"),
                                frek_memorije = Request.Params.Get("frek_memorije"),
                                frek_jezgre = Request.Params.Get("frek_jezgre"),
                                potrosnja = Request.Params.Get("potrosnja"),
                            };
                            dbc.Graficke.Add(gr);
                            break;
                        case "maticne":
                            Maticne ma = new Maticne() {
                                oglas_id = oglasi.Id,
                                proizvodac = Request.Params.Get("proizvodac"),
                                model = Request.Params.Get("model"),
                                socket = Request.Params.Get("socket"),
                                potrosnja = Request.Params.Get("potrosnja"),
                                memorija = Request.Params.Get("memorija"),
                            };
                            dbc.Maticne.Add(ma);
                            break;
                        case "memorije":
                            Memorije me = new Memorije() {
                                oglas_id = oglasi.Id,
                                proizvodac = Request.Params.Get("proizvodac"),
                                model = Request.Params.Get("model"),
                                tip = Request.Params.Get("tip"),
                                frekvencija = Request.Params.Get("frekvencija"),
                                velicina = Request.Params.Get("velicina"),
                            };
                            dbc.Memorije.Add(me);
                            break;
                        case "pohrana":
                            Pohrana po = new Pohrana() {
                                oglas_id = oglasi.Id,
                                proizvodac = Request.Params.Get("proizvodac"),
                                model = Request.Params.Get("model"),
                                rpm = Request.Params.Get("rpm"),
                                sata_ver = Request.Params.Get("sata_ver"),
                                velicina = Request.Params.Get("velicina"),
                                brzina_cit = Request.Params.Get("brzina_cit"),
                                brzina_pis = Request.Params.Get("brzina_pis"),
                            };
                            dbc.Pohrana.Add(po);
                            break;
                        case "procesori":
                            Procesori pr = new Procesori() {
                                oglas_id = oglasi.Id,
                                proizvodac = Request.Params.Get("proizvodac"),
                                model = Request.Params.Get("model"),

Oglasnik/Views/Oglasi/Maticne.cshtml
@using Oglasnik.Helpers
@model IEnumerable<Oglasnik.Models.Maticne>

@{
    ViewBag.Title = "Matične ploče";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

<div class="hidden-xs col-sm-4 col-lg-3">
    <div class="container"><a href="" id="reset">Reset</a></div>
    @Html.SpecFilter(Model.Select(m => m.proizvodac).Distinct(), m => m.proizvodac)
    @Html.SpecFilter(Model.Select(m => m.model).Distinct(), m => m.model)
    @Html.SpecFilter(Model.Select(m => m.socket).Distinct(), m => m.socket)
    @Html.SpecFilter(Model.Select(m => m.potrosnja).Distinct(), m => m.potrosnja)
    @Html.SpecFilter(Model.Select(m => m.memorija).Distinct(), m => m.memorija)
</div>

<div class="col-xs-12 col-sm-8 col-lg-9">
    <div class="row">
        <div class="container-fluid">
            <div class="col-xs-6">
                <label>Broj oglasa koji odgovaraju kriterijima:</label><br />
                <span id="crit_count"></span> / @Model.Count()
            </div>
            <div class="col-xs-3 col-xs-offset-3">
                <label>Oglasa po stranici:</label>
                <input type="number" class="form-control" id="splitBy" value="3" min="1" />
            </div>
        </div>
    </div>

    @foreach (var item in Model) {
        <div class="panel panel-success oglas" data-oglas="@Json.Encode(item)" style="display:none">
            <div class="panel-heading">
                <span class="panel-title" data-toggle="popover" title="Opis">
                    @Html.ActionLink(item.oglas.naslov, "Details", "Oglasi", new { id = item.oglas.Id }, null)
                    <span class="pull-right">@Html.DisplayFor(modelItem => item.oglas.datum_objave)</span>
                </span>
            </div>
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.proizvodac)</strong>: @Html.DisplayFor(modelItem => item.proizvodac)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.model)</strong>: @Html.DisplayFor(modelItem => item.model)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.socket)</strong>: @Html.DisplayFor(modelItem => item.socket)</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.potrosnja)</strong>: @Html.DisplayFor(modelItem => item.potrosnja)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.memorija)</strong>: @Html.DisplayFor(modelItem => item.memorija)</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                &nbsp;<span class="pull-right">@Html.DisplayNameFor(m => m.oglas.cijena): @Html.DisplayFor(modelItem => item.oglas.cijena) kn</span>
            </div>
        </div>
    }

    <nav>
        <ul class="pagination">
            <li id="prev">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li id="next">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/filtriranje-oglasa.js")
}

Oglasnik/Views/Oglasi/Memorije.cshtml
@using Oglasnik.Helpers
@model IEnumerable<Oglasnik.Models.Memorije>

@{
    ViewBag.Title = "Memorije";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

<div class="hidden-xs col-sm-4 col-lg-3">
    <div class="container"><a href="" id="reset">Reset</a></div>
    @Html.SpecFilter(Model.Select(m => m.proizvodac).Distinct(), m => m.proizvodac)
    @Html.SpecFilter(Model.Select(m => m.model).Distinct(), m => m.model)
    @Html.SpecFilter(Model.Select(m => m.tip).Distinct(), m => m.tip)
    @Html.SpecFilter(Model.Select(m => m.frekvencija).Distinct(), m => m.frekvencija)
    @Html.SpecFilter(Model.Select(m => m.velicina).Distinct(), m => m.velicina)
</div>

<div class="col-xs-12 col-sm-8 col-lg-9">
    <div class="row">
        <div class="container-fluid">
            <div class="col-xs-6">
                <label>Broj oglasa koji odgovaraju kriterijima:</label><br />
                <span id="crit_count"></span> / @Model.Count()
            </div>
            <div class="col-xs-3 col-xs-offset-3">
                <label>Oglasa po stranici:</label>
                <input type="number" class="form-control" id="splitBy" value="3" min="1" />
            </div>
        </div>
    </div>

    @foreach (var item in Model) {
        <div class="panel panel-success oglas" data-oglas="@Json.Encode(item)" style="display:none">
            <div class="panel-heading">
                <span class="panel-title" data-toggle="popover" title="Opis">
                    @Html.ActionLink(item.oglas.naslov, "Details", "Oglasi", new { id = item.oglas.Id }, null)
                    <span class="pull-right">@Html.DisplayFor(modelItem => item.oglas.datum_objave)</span>
                </span>
            </div>
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.proizvodac)</strong>: @Html.DisplayFor(modelItem => item.proizvodac)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.model)</strong>: @Html.DisplayFor(modelItem => item.model)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.tip)</strong>: @Html.DisplayFor(modelItem => item.tip)</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.frekvencija)</strong>: @Html.DisplayFor(modelItem => item.frekvencija)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.velicina)</strong>: @Html.DisplayFor(modelItem => item.velicina)</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                &nbsp;<span class="pull-right">@Html.DisplayNameFor(m => m.oglas.cijena): @Html.DisplayFor(modelItem => item.oglas.cijena) kn</span>
            </div>
        </div>
    }

    <nav>
        <ul class="pagination">
            <li id="prev">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li id="next">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/filtriranje-oglasa.js")
}

Oglasnik/Views/Oglasi/Pohrana.cshtml
@using Oglasnik.Helpers
@model IEnumerable<Oglasnik.Models.Pohrana>

@{
    ViewBag.Title = "Pohrana";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

<div class="hidden-xs col-sm-4 col-lg-3">
    <div class="container"><a href="" id="reset">Reset</a></div>
    @Html.SpecFilter(Model.Select(m => m.proizvodac).Distinct(), m => m.proizvodac)
    @Html.SpecFilter(Model.Select(m => m.model).Distinct(), m => m.model)
    @Html.SpecFilter(Model.Select(m => m.rpm).Distinct(), m => m.rpm)
    @Html.SpecFilter(Model.Select(m => m.sata_ver).Distinct(), m => m.sata_ver)
    @Html.SpecFilter(Model.Select(m => m.velicina).Distinct(), m => m.velicina)
    @Html.SpecFilter(Model.Select(m => m.brzina_cit).Distinct(), m => m.brzina_cit)
    @Html.SpecFilter(Model.Select(m => m.brzina_pis).Distinct(), m => m.brzina_pis)
</div>

<div class="col-xs-12 col-sm-8 col-lg-9">
    <div class="row">
        <div class="container-fluid">
            <div class="col-xs-6">
                <label>Broj oglasa koji odgovaraju kriterijima:</label><br />
                <span id="crit_count"></span> / @Model.Count()
            </div>
            <div class="col-xs-3 col-xs-offset-3">
                <label>Oglasa po stranici:</label>
                <input type="number" class="form-control" id="splitBy" value="3" min="1" />
            </div>
        </div>
    </div>

    @foreach (var item in Model) {
        <div class="panel panel-success oglas" data-oglas="@Json.Encode(item)" style="display:none">
            <div class="panel-heading">
                <span class="panel-title" data-toggle="popover" title="Opis">
                    @Html.ActionLink(item.oglas.naslov, "Details", "Oglasi", new { id = item.oglas.Id }, null)
                    <span class="pull-right">@Html.DisplayFor(modelItem => item.oglas.datum_objave)</span>
                </span>
            </div>
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.proizvodac)</strong>: @Html.DisplayFor(modelItem => item.proizvodac)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.model)</strong>: @Html.DisplayFor(modelItem => item.model)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.rpm)</strong>: @Html.DisplayFor(modelItem => item.rpm)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.sata_ver)</strong>: @Html.DisplayFor(modelItem => item.sata_ver)</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.velicina)</strong>: @Html.DisplayFor(modelItem => item.velicina)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.brzina_cit)</strong>: @Html.DisplayFor(modeliItem => item.brzina_cit)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.brzina_pis)</strong>: @Html.DisplayFor(modelItem => item.brzina_pis)</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                &nbsp;<span class="pull-right">@Html.DisplayNameFor(m => m.oglas.cijena): @Html.DisplayFor(modelItem => item.oglas.cijena) kn</span>
            </div>
        </div>
    }

    <nav>
        <ul class="pagination">
            <li id="prev">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li id="next">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/filtriranje-oglasa.js")
}

Oglasnik/Views/Oglasi/Psu.cshtml
@using Oglasnik.Helpers
@model IEnumerable<Oglasnik.Models.Psu>

@{
    ViewBag.Title = "Napajanja";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

<div class="hidden-xs col-sm-4 col-lg-3">
    <div class="container"><a href="" id="reset">Reset</a></div>
    @Html.SpecFilter(Model.Select(m => m.proizvodac).Distinct(), m => m.proizvodac)
    @Html.SpecFilter(Model.Select(m => m.model).Distinct(), m => m.model)
    @Html.SpecFilter(Model.Select(m => m.snaga).Distinct(), m => m.snaga)
</div>

<div class="col-xs-12 col-sm-8 col-lg-9">
    <div class="row">
        <div class="container-fluid">
            <div class="col-xs-6">
                <label>Broj oglasa koji odgovaraju kriterijima:</label><br />
                <span id="crit_count"></span> / @Model.Count()
            </div>
            <div class="col-xs-3 col-xs-offset-3">
                <label>Oglasa po stranici:</label>
                <input type="number" class="form-control" id="splitBy" value="3" min="1" />
            </div>
        </div>
    </div>

    @foreach (var item in Model) {
        <div class="panel panel-success oglas" data-oglas="@Json.Encode(item)" style="display:none">
            <div class="panel-heading">
                <span class="panel-title" data-toggle="popover" title="Opis">
                    @Html.ActionLink(item.oglas.naslov, "Details", "Oglasi", new { id = item.oglas.Id }, null)
                    <span class="pull-right">@Html.DisplayFor(modelItem => item.oglas.datum_objave)</span>
                </span>
            </div>
            <div class="panel-body">
                <div class="container-fluid">
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.proizvodac)</strong>: @Html.DisplayFor(modelItem => item.proizvodac)</li>
                            <li><strong>@Html.DisplayNameFor(m => m.model)</strong>: @Html.DisplayFor(modelItem => item.model)</li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <ul>
                            <li><strong>@Html.DisplayNameFor(m => m.snaga)</strong>: @Html.DisplayFor(modelItem => item.snaga)</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                &nbsp;<span class="pull-right">@Html.DisplayNameFor(m => m.oglas.cijena): @Html.DisplayFor(modelItem => item.oglas.cijena) kn</span>
            </div>
        </div>
    }

    <nav>
        <ul class="pagination">
            <li id="prev">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li id="next">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/filtriranje-oglasa.js")
}